source = $HOME/.config/hypr/conf/env.conf
source = $HOME/.config/hypr/conf/monitors.conf
source = $HOME/.config/hypr/conf/input.conf
source = $HOME/.config/hypr/conf/general.conf
source = $HOME/.config/hypr/conf/binds.conf
source = $HOME/.config/hypr/conf/autostart.conf
