$mod = SUPER

# terminal
bind = $mod, RETURN, exec, kitty

# launcher
bind = $mod, SPACE, exec, rofi -show drun

# swaync control centre
bind = $mod, N, exec, swaync-client -t

# power menu
bind = $mod, ESCAPE, exec, sh -c '/home/jacob/.local/bin/powermenu >/dev/null 2>&1'

# thunar file explorer
bind = $mod, E, exec, thunar

# close window
bind = $mod, Q, killactive

# reload hyprland conf
bind = $mod SHIFT, R, exec, hyprctl reload

# force exit hyprland
bind = $mod SHIFT, E, exit

# screenshot area with swappy
bind = $mod SHIFT, S, exec, grim - | swappy -f -

# rofi clipboard picker
bind = $mod, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# workspace switching
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10


# move window to workspace
bind = $mod SHIFT, 1, movetoworkspace, 1
bind = $mod SHIFT, 2, movetoworkspace, 2
bind = $mod SHIFT, 3, movetoworkspace, 3
bind = $mod SHIFT, 4, movetoworkspace, 4
bind = $mod SHIFT, 5, movetoworkspace, 5
bind = $mod SHIFT, 6, movetoworkspace, 6
bind = $mod SHIFT, 7, movetoworkspace, 7
bind = $mod SHIFT, 8, movetoworkspace, 8
bind = $mod SHIFT, 9, movetoworkspace, 9
bind = $mod SHIFT, 10, movetoworkspace, 10

# focus movement
bind = $mod, H, movefocus, l
bind = $mod, L, movefocus, r
bind = $mod, K, movefocus, u
bind = $mod, J, movefocus, d

# move windows
bind = $mod SHIFT, H, movewindow, l
bind = $mod SHIFT, L, movewindow, r
bind = $mod SHIFT, K, movewindow, u
bind = $mod SHIFT, J, movewindow, d

# togle floating
bind = $mod, F, togglefloating

# scroll bar to prev or next workspace
bind = $mod, mouse_down, workspace, r-1
bind = $mod, mouse_up, workspace, r+1
